### ISSUE TITLE
Authentication Failed,

### ISSUE THREAD

**Issue by lodhiyuvraj** [Arkitecht/FedEx-php#1]
How to Change url for Production and Test because my authentication parameter correct 
 but got error "Authentication Failed " may be this is URL issue ??

RateReply {#368 ▼
  +HighestSeverity: "ERROR"
  +Notifications: array:1 [▼
    0 => Notification {#369 ▼
      +Severity: "ERROR"
      +Source: "prof"
      +Code: "1000"
      +Message: "Authentication Failed"
      +LocalizedMessage: null
      +MessageParameters: null
    }
  ]
  +Version: VersionId {#370 ▼
    +ServiceId: "crs"
    +Major: 18
    +Intermediate: 0
    +Minor: 0
  }
  +TransactionDetail: null
  +RateReplyDetails: null

**Comment by Arkitecht** [comment]
The third parameter of the service is a boolean, which indicates if it should use the beta service.
IE:
```$rateService = new RateService($wsdlOptions, true, true);```
